name: Make documents

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          version: 3.1.2
      - name: Install dependencies
        run: |
          apt install pdflatex
      - name: Run make
        run: make
      - name: Create PR
        uses: peter-evans/create-pull-request@v6

